# This is a basic workflow to help you get started with Actions

name: test and build

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "master" branch
  push:
    branches: ["main"]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

permissions:
  contents: read

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  test_and_build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4

      # Runs a single command using the runners shell
      - name: Setup python 3.12
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      # Runs a set of commands using the runners shell
      - name: Install dependencies
        run: |
          pip install -r app/requirements.txt
          pip install pytest==8.2.0 httpx==0.28.0 pytest-asyncio==1.2.0 pytest-cov==5.0.0 ruff bandit safety
      # Runs test
      - name: Run tests
        working-directory: ./app
        env:
          PYTHONPATH: /app # LA SOLUCIÃ“N (igual que Docker)
        run: pytest tests/ --cov=main --cov-report=xml

      # Runs
      - name: Lint with Ruff
        run: ruff check .

      - name: Security scan
        run: |
          bandit -r . -q
          safety check
